name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - uses: libsdl-org/setup-sdl@main
      id: sdl
      with:
        install-linux-dependencies: true
        version: 2-latest

    - name: Build
      run: make release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: trip8-${{matrix.os}}
        path: ${{github.workspace}}/trip8*
